# -*- coding: utf-8 -*-
"""automate_RahmaHidayatiFitrah.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8C77QO9qCN0w3EnFB8giFxLCDGep5_g
"""

# ================================================================
# Fungsi otomatisasi preprocessing Wine Quality Dataset
# Nama: Rahma Hidayati Fitrah
# ================================================================

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

def load_data():
    url_red   = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
    url_white = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv"

    df_red   = pd.read_csv(url_red, sep=';')
    df_white = pd.read_csv(url_white, sep=';')

    df_red['type']   = 0
    df_white['type'] = 1

    df = pd.concat([df_red, df_white], ignore_index=True)
    print(f"Data loaded: {df.shape[0]} baris, {df.shape[1]} kolom")
    return df


def remove_duplicates(df):
    before = df.shape[0]
    df = df.drop_duplicates()
    after = df.shape[0]
    print(f"Hapus duplikat: {before} → {after} baris ({before-after} dihapus)")
    return df


def remove_outliers_iqr(df, columns):
    df_clean = df.copy()
    before = df_clean.shape[0]
    for col in columns:
        Q1 = df_clean[col].quantile(0.25)
        Q3 = df_clean[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        df_clean = df_clean[
            (df_clean[col] >= lower) & (df_clean[col] <= upper)
        ]
    print(f"Hapus outlier (IQR): {before} → {df_clean.shape[0]} baris")
    return df_clean


def split_and_scale(df):
    X = df.drop('quality', axis=1)
    y = df['quality']

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    print(f"Split: Train={X_train.shape[0]} | Test={X_test.shape[0]}")

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled  = scaler.transform(X_test)
    print("Standarisasi selesai")

    df_train = pd.DataFrame(X_train_scaled, columns=X.columns)
    df_train['quality'] = y_train.values

    df_test = pd.DataFrame(X_test_scaled, columns=X.columns)
    df_test['quality'] = y_test.values

    return df_train, df_test


def save_data(df_train, df_test):
    df_train.to_csv('winequality_preprocessing.csv', index=False)
    df_test.to_csv('winequality_test.csv', index=False)
    print("File disimpan:")
    print("   - winequality_preprocessing.csv")
    print("   - winequality_test.csv")


def main():
    print("=" * 50)
    print("AUTOMATE PREPROCESSING - Wine Quality Dataset")
    print("=" * 50)

    df = load_data()

    df = remove_duplicates(df)

    feature_cols = [col for col in df.columns if col != 'quality']
    df = remove_outliers_iqr(df, feature_cols)

    df_train, df_test = split_and_scale(df)

    save_data(df_train, df_test)

    print("\nPipeline preprocessing selesai!")
    print(f"   Train shape: {df_train.shape}")
    print(f"   Test shape : {df_test.shape}")

    return df_train, df_test


if __name__ == "__main__":
    main()